// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxoyeytjuhgshakandzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4b3lleXRqdWhnc2hha2FuZHpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5NTI4NjQsImV4cCI6MjA4OTUyODg2NH0.9yTZf-Qve4Zqh2mXx1uuHApHVmgBtyVMLESPkno5k3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});